name: Validate Dependencies

on:
  workflow_call:
    inputs:
      is_prerelease:
        description: 'Allow RC versions for a prerelease'
        required: true
        type: boolean
      release_branch:
        description: 'Release branch containing versions.yaml'
        required: true
        type: string

jobs:
  validate-deps:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.release_branch }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ci/.nvmrc

      - name: Install CI dependencies
        working-directory: ci
        run: npm ci

      - name: Check versions.yaml entries are semver-compatible
        working-directory: ci
        run: npm run release:check-versions-yaml
        env:
          REPO_ROOT: ${{ github.workspace }}
          IS_PRERELEASE: ${{ inputs.is_prerelease }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}